In [21]:
import torch
from torch.nn import Linear, functional as F
from torch.optim import SGD

In [22]:
class LinearRegression(Linear):
    def __init__(self, in_features, out_features = 1, bias = True):
        super().__init__(in_features= in_features, out_features=out_features, bias=bias)
        self.optimizer = torch.optim.Adam(self.parameters(), lr=0.00005)
    
    def fit(self, train_dl, num_epochs=100):
        for epoch in range(num_epochs+1):
            for x_batch, y_batch in train_dl:
                self.prediction = self(x_batch.float())
                loss = F.mse_loss(self.prediction, y_batch.float())
                loss.backward()
                self.optimizer.step()
                self.optimizer.zero_grad()
                
            if epoch % 10 == 0:
                print(f'Epoch {epoch}, Loss: {loss}')
        

In [ ]:
df = pd.read_csv('data.csv')
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
506  0.98765   0.0  12.50     0  0.561  6.980  89.0  2.0980    3  320   
507  0.23456   0.0  12.50     0  0.561  6.980  76.0  2.6540    3  320   
508  0.44433   0.0  12.50     0  0.561  6.123  98.0  2.9870    3  320   
509  0.77763   0.0  12.70     0  0.561  6.222  34.0  2.5430    3  329   
510  0.65432   0.0  12.80     0  0.561  6.760  67.0  2.9870    3  345   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
506     23.0  396.00  12.00  12.0  
507     23.0  343.00  25.00  32.0  
508     23.0  343.00  21.00  54.0  
509     23.0  343.00  76.00  67.0  
510     23.0  321.00  45.00  24.0  

[511 rows x 14 columns]

In [ ]:
X = df[df.columns[:-1]].values
y = df[df.columns[-1]].values

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
class LinearRegression_numpy():
    def __init__(self, in_features, out_features, bias = True):
        self.weight = np.random.rand(in_features, out_features)
        self.bias = np.random.rand(out_features)
    
    def __loss_fn(self, y_predicted, target):
        return np.abs(y_predicted - target)
    
    def predict(self, X):
        return np.matmul(X, self.weight) + self.bias
    
    def fit(self, X, y, num_epochs, lr):
        for epoch in range(num_epochs):
            for index in range(len(X)):
                
                x_value, y_value = X[index], y[index]
                predicted = self.predict(x_value)
                loss = self.__loss_fn(predicted, y_value)
                # print(loss)
                if loss == 0: return
                
                direction = 2 * np.sum((self.predict(x_value) - y_value )* x_value)
                self.weight -= lr*direction
                # self.bias -= lr*direction
            
            if epoch % 10 == 0:
                print(f'Epoch {epoch}, Loss: {loss}')     

In [ ]:
w = LinearRegression_numpy(13, 1)

In [ ]:
X.transpose()

array([[6.3200e-03, 2.7310e-02, 2.7290e-02, ..., 4.4433e-01, 7.7763e-01,
        6.5432e-01],
       [1.8000e+01, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.3100e+00, 7.0700e+00, 7.0700e+00, ..., 1.2500e+01, 1.2700e+01,
        1.2800e+01],
       ...,
       [1.5300e+01, 1.7800e+01, 1.7800e+01, ..., 2.3000e+01, 2.3000e+01,
        2.3000e+01],
       [3.9690e+02, 3.9690e+02, 3.9283e+02, ..., 3.4300e+02, 3.4300e+02,
        3.2100e+02],
       [4.9800e+00, 9.1400e+00, 4.0300e+00, ..., 2.1000e+01, 7.6000e+01,
        4.5000e+01]])

In [ ]:
len([X[0]])

1

In [ ]:
w.predict(X[0])

array([488.4863361])

In [ ]:
y[0]

24.0

In [ ]:
w.weight

array([[0.34143995],
       [0.77777323],
       [0.41756339],
       [0.55822897],
       [0.69932086],
       [0.69232665],
       [0.06350007],
       [0.07459961],
       [0.63478353],
       [0.67218797],
       [0.69587041],
       [0.63224872],
       [0.44750016]])

In [ ]:
X[0].reshape(13, 1).transpose()

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [ ]:
w.fit(X,y,100, 0.0005)

Epoch 0, Loss: [nan]
Epoch 10, Loss: [nan]
Epoch 20, Loss: [nan]
Epoch 30, Loss: [nan]
Epoch 40, Loss: [nan]
Epoch 50, Loss: [nan]
Epoch 60, Loss: [nan]
Epoch 70, Loss: [nan]
Epoch 80, Loss: [nan]
Epoch 90, Loss: [nan]


In [ ]:
w.bias, w.weight

(array([0.72878011]),
 array([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan]]))

In [410]:
sum(np.dot(X[0].reshape(1, 13).transpose(), np.array([1]).reshape(1, 1)))

array([810.89932])

In [411]:
np.array([1]).reshape(1, 1)

array([[1]])

In [ ]:
a = np.array([[1,2],[1,2]])

In [ ]:
b = np.array([1, 2])

In [ ]:
a.shape, b.shape

((2, 2), (2,))

In [ ]:
np.matmul(a, b)

array([5, 5])

In [ ]:
w.predict(X[0]).shape

(1,)

In [ ]:
X[0].reshape(1, 13).shape

(1, 13)

In [ ]:
sum(X[0] *  (w.predict(X[0]) + w.bias.bias+ w.bias - y[0]))

array([[-2.35707662],
       [-3.05192265],
       [-2.3648045 ],
       [-2.55913911],
       [-2.59080062],
       [-2.92067035],
       [-2.94927517],
       [-2.73578019],
       [-2.25741072],
       [-2.38753177],
       [-3.09511769],
       [-2.91513507],
       [-2.30912236]])

In [ ]:
(w.predict(X[0]) - y[0])

array([400.08193474])

In [ ]:
y[0]

24.0

In [ ]:
w.predict(X[0])

array([424.08193474])